import { createContext, useContext, useState } from "react";

type Language = "ru" | "en" | "kz";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Complete translations for all three languages
const translations = {
  ru: {
    // Navigation
    "nav.services": "Услуги",
    "nav.news": "Новости", 
    "nav.about": "О компании",
    "nav.contacts": "Контакты",
    "nav.dashboard": "Панель управления",
    "auth.login": "Войти",
    "auth.logout": "Выйти",
    
    // News Section
    "news.title": "Новости и публикации",
    "news.subtitle": "Актуальные материалы о трендах ESG, устойчивом развитии и лучших практиках российского и международного рынка",
    "news.badge": "2025 Новости",
    "news.new": "Новое",
    "news.blog": "Блог",
    "news.view_all": "Все новости",
    "news.read_time": "мин",
    
    // News Articles
    "news.article1.title": "Новые требования к ESG-отчётности в России: что изменится в 2025 году",
    "news.article1.description": "Центральный банк России представил обновлённые стандарты ESG-отчётности для крупных публичных компаний",
    "news.article1.readTime": "3",
    
    "news.article2.title": "Устойчивое финансирование: как ESG-критерии влияют на инвестиционные решения",
    "news.article2.description": "Анализ тенденций зелёного финансирования и влияния ESG-рейтингов на стоимость капитала российских компаний",
    "news.article2.readTime": "5",
    
    "news.article3.title": "Цифровизация ESG-процессов: как технологии помогают компаниям достигать целей устойчивого развития",
    "news.article3.description": "Обзор digital-решений для автоматизации сбора ESG-данных и повышения прозрачности отчётности",
    "news.article3.readTime": "4",
    
    "news.article4.title": "Практические рекомендации по внедрению ESG-стратегии для малого и среднего бизнеса",
    "news.article4.description": "Пошаговое руководство по интеграции ESG-принципов в операционную деятельность компаний МСБ",
    "news.article4.readTime": "6",
    
    // Contacts Section
    "contacts.title": "Первый шаг к трансформации вашего бизнеса начинается здесь",
    "contacts.subtitle": "Точка старта любого ESG-проекта в Sustainable Compass",
    "contacts.email_placeholder": "Ваша корпоративная почта",
    "contacts.info_title": "Контактная информация",
    "contacts.email": "Email",
    "contacts.phone": "Телефон",
    "contacts.address": "Адрес",
    "contacts.address_text": "Республика Казахстан, г. Алматы\nул. Жибек Жолы 135, офис 3 этаж",
    "contacts.problems_title": "С какими проблемами сталкиваются компании до работы с Sustainable Compass?",
    "contacts.esg_title": "ESG — это не только экология",
    "contacts.esg_subtitle": "Это целостный подход",
    "contacts.problems.1": "Не понимаю, как начать углубляться в business вопросы",
    "contacts.problems.2": "Не хватает экспертов на глубину диагностику",
    "contacts.problems.3": "Требования по ESG растут, а вы не готовы?",
    "contacts.problems.4": "Клиенты всё сложнее найти из-за новых ESG норм позиций",
    "contacts.problems.5": "Банки работают не так, как соблюдение всех новых экологичных норм",
    "contacts.problems.6": "Коллеги стали требовать не только цену продукта",
    
    // Footer
    "footer.copyright": "© 2024 Sustainable Compass. Все права защищены.",
    "footer.links": "Политика конфиденциальности • Условия использования • Поддержка",
    
    // Pricing General
    "pricing.title": "Планы IT-решений для вашего бизнеса",
    "pricing.subtitle": "Выберите подходящий план технологических решений для цифровой трансформации вашей компании и внедрения ESG стандартов",
    "pricing.details": "Посмотреть, что включает ▼",
    "pricing.additional.title": "Дополнительные преимущества наших планов",
    "pricing.additional.subtitle": "Независимо от выбранного плана, вы получаете полный спектр поддержки",
    "pricing.consultation.title": "Персональная консультация",
    "pricing.consultation.desc": "Бесплатная первичная консультация с экспертом по ESG для анализа ваших потребностей",
    "pricing.training.title": "Обучение команды",
    "pricing.training.desc": "Комплексное обучение ваших сотрудников работе с ESG системами и стандартами",
    "pricing.security.title": "Безопасность данных",
    "pricing.security.desc": "Высочайший уровень защиты корпоративных данных согласно международным стандартам",
    "pricing.trial": "Все планы включают бесплатный пробный период 14 дней",
    "pricing.payment": "Возможна оплата в рассрочку • Скидки для образовательных учреждений • Гибкие условия для стартапов",
    
    // Pricing Plans - Russian
    "pricing.plans.startup.name": "Стартап",
    "pricing.plans.startup.subtitle": "Базовые IT-решения",
    "pricing.plans.startup.employees": "до 50 сотрудников",
    "pricing.plans.startup.feature1": "Базовая ESG диагностика",
    "pricing.plans.startup.feature2": "Облачное хранение 500 ГБ",
    "pricing.plans.startup.feature3": "Техподдержка 24/7",
    "pricing.plans.startup.feature4": "Автоматические отчеты",
    "pricing.plans.startup.feature5": "API интеграция",
    
    "pricing.plans.avantgard.name": "Avantgard",
    "pricing.plans.avantgard.subtitle": "Продвинутые решения с ИИ",
    "pricing.plans.avantgard.employees": "50-500 сотрудников",
    "pricing.plans.avantgard.feature1": "ESG аналитика с ИИ",
    "pricing.plans.avantgard.feature2": "Облачное хранение 500 ГБ",
    "pricing.plans.avantgard.feature3": "Техподдержка 24/7",
    "pricing.plans.avantgard.feature4": "Автоматизированные отчеты",
    "pricing.plans.avantgard.feature5": "API интеграция",
    "pricing.plans.avantgard.feature6": "ИИ блокчейн",
    
    "pricing.plans.quantum.name": "Quantum",
    "pricing.plans.quantum.subtitle": "Интеллектуальное управление",
    "pricing.plans.quantum.employees": "500+ сотрудников",
    "pricing.plans.quantum.feature1": "Полная ESG экосистема",
    "pricing.plans.quantum.feature2": "Неограниченное хранение",
    "pricing.plans.quantum.feature3": "Приоритетная поддержка",
    "pricing.plans.quantum.feature4": "Персональный менеджер",
    "pricing.plans.quantum.feature5": "Корпоративная интеграция",
    
    "pricing.plans.enterprise.name": "Enterprise+",
    "pricing.plans.enterprise.subtitle": "Эксклюзивные решения",
    "pricing.plans.enterprise.employees": "Корпорации и госсектор",
    "pricing.plans.enterprise.feature1": "Индивидуальная разработка",
    "pricing.plans.enterprise.feature2": "Выделенная инфраструктура",
    "pricing.plans.enterprise.feature3": "Персональная команда",
    "pricing.plans.enterprise.feature4": "SLA 99.9%",
    "pricing.plans.enterprise.feature5": "Комплексная безопасность",
    
    // ESG Components
    "esg.environmental.title": "Environmental",
    "esg.environmental.subtitle": "Экологическая составляющая",
    "esg.environmental.items.1": "Экологическая отчетность",
    "esg.environmental.items.2": "Управление отходами",
    "esg.environmental.items.3": "Энергоэффективность",
    "esg.environmental.items.4": "Климат",
    "esg.environmental.items.5": "Биоразнообразие",
    "esg.social.title": "Social",
    "esg.social.subtitle": "Социальная составляющая",
    "esg.social.items.1": "Развитие человеческого капитала",
    "esg.social.items.2": "Охрана труда и безопасность",
    "esg.social.items.3": "Социальные инвестиции",
    "esg.social.items.4": "Этика",
    "esg.social.items.5": "Права человека",
    "esg.governance.title": "Governance",
    "esg.governance.subtitle": "Корпоративное управление",
    "esg.governance.items.1": "Корпоративное управление",
    "esg.governance.items.2": "Этические принципы",
    "esg.governance.items.3": "Управление рисками",
    "esg.governance.items.4": "Прозрачность",
    "esg.governance.items.5": "Антикоррупционная политика",
    
    // Authentication
    "auth.authorization": "Авторизация",
    "auth.loginOrRegisterDescription": "Войдите в личный кабинет или создайте новый аккаунт для доступа к ESG платформе",
    "auth.register": "Регистрация",
    "auth.loginTitle": "Вход в личный кабинет",
    "auth.loginDescription": "Получите доступ к анализу ESG диагностики и персональным рекомендациям",
    "auth.registerTitle": "Создать аккаунт",
    "auth.registerDescription": "Заполните информацию для доступа к ESG диагностике",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.loginButton": "Войти",
    "auth.forgotPassword": "Забыли пароль или логин?",
    "auth.contactSupport": "Напишите на",
    "auth.demoAccess": "Демо-доступ",
    "auth.invalidCredentials": "Неверный email или пароль",
    "auth.fullName": "Полное имя",
    "auth.fullNamePlaceholder": "Иван Иванов",
    "auth.phone": "Телефон",
    "auth.position": "Должность",
    "auth.positionPlaceholder": "Специалист по устойчивому развитию",
    "auth.companyInfo": "Информация о компании",
    "auth.companyName": "Название компании",
    "auth.companyNamePlaceholder": "ПАО «Газпром Нефтехим»",
    "auth.industry": "Область",
    "auth.selectIndustry": "Выберите область",
    "auth.industries.energy": "Энергетика",
    "auth.industries.manufacturing": "Производство",
    "auth.industries.finance": "Финансы",
    "auth.industries.tech": "Технологии",
    "auth.industries.other": "Другое",
    "auth.companySize": "Размер компании",
    "auth.selectSize": "Выберите размер",
    "auth.companySizes.small": "До 50 сотрудников",
    "auth.companySizes.medium": "50-250 сотрудников",
    "auth.companySizes.large": "250-1000 сотрудников",
    "auth.companySizes.enterprise": "Более 1000 сотрудников",
    "auth.city": "Город",
    "auth.cityPlaceholder": "Москва, Казахстан",
    "auth.confirmPassword": "Подтвердить пароль",
    "auth.createAccount": "Создать аккаунт",
    
    // Dashboard
    "dashboard.welcome": "Добро пожаловать, Айгуль Нурданова!",
    "dashboard.companyAnalysis": "ESG-анализ компании «Зеленые Технологии Алматы»",
    "dashboard.registration": "Регистрация",
    "dashboard.completion": "Заполнение",
    "dashboard.progressAnalysis": "Анализ прогресса",
    "dashboard.clientReport": "Отчет для клиентов",
    "dashboard.esgDiagnosticsBase": "Базы ESG диагностики",
    "dashboard.esgAssessment": "Оценка экологического, социального и управленческого развития",
    "dashboard.esgCompanyAnalysis": "ESG Analysis компаний",
    "dashboard.new": "Новая",
    "dashboard.comprehensiveAnalysis": "Комплексный анализ показателей социальной, экологической и управленческой деятельности",
    "dashboard.completed": "Заполнено 26 из 36 вопросов",
    "dashboard.daysAgo": "15 дней назад",
    "dashboard.monthsRemaining": "До конца 11 месяц",
    "dashboard.smartPlasticZone": "Smart Plastic Zone",
    "dashboard.completedStatus": "Выполнено",
    "dashboard.environmentalSafety": "Оценка промежуточной или окончательной экологической безопасности",
    "dashboard.completed34": "Заполнено 34 из 39 вопросов",
    "dashboard.dayAgo": "1 день назад",
    "dashboard.endMarch": "конец 15 марта",
    "dashboard.greenBuildingAssessment": "Green Building Assessment",
    "dashboard.inProgress": "В процессе",
    "dashboard.buildingEfficiency": "Оценка экологической эффективности зданий и сооружений",
    "dashboard.completed7": "Заполнено 7 из 24 вопросов",
    "dashboard.continue": "Продолжить",
    "dashboard.quickActions": "Быстрые действия",
    "dashboard.startNewDiagnostics": "Начать новую диагностику",
    "dashboard.downloadReports": "Скачать отчеты",
    "dashboard.contactSupport": "Связаться с поддержкой",
    "dashboard.personalInfo": "Личная информация",
    "dashboard.email": "Email:",
    "dashboard.dateJoined": "Январь: 15:47-2024",
    "dashboard.profileConfirmation": "Подтверждение профиля",
    "dashboard.companyInfo": "Информация о компании",
    "dashboard.companyName": "ТОО \"Зеленые Технологии Алматы\"",
    "dashboard.ecologyForAll": "Экология для всех:",
    "dashboard.location": "Алматы, Казахстан",
    "dashboard.employees": "50-100 сотрудников",
    "dashboard.website": "www.greentech-almaty.kz",
    "dashboard.companyConfirmation": "Подтверждение компании",
    "dashboard.downloadAllReports": "Скачать все отчеты",
    
    // Hero Section
    "hero.title": "Sustainable Compass",
    "hero.subtitle": "Цифровая платформа для оценки и улучшения ESG-показателей",
    "hero.description": "Комплексная диагностика бизнес-процессов, ESG-анализ по международным стандартам и персонализированные рекомендации для устойчивого развития вашей компании",
    "hero.cta": "Попробовать бесплатно",
    "hero.demo": "О платформе",
    "hero.stats_diagnostics": "проведено диагностик",
    "hero.feature1": "Быстрая ESG диагностика",
    "hero.feature2": "Персонализированные рекомендации",
    "hero.feature3": "Визуальные отчеты для инвесторов",
    "hero.feature4": "Международные стандарты",
    
    // Stats Section
    "stats.companies": "компаний",
    "stats.companies_desc": "уже используют нашу платформу",
    "stats.reports": "отчетов",
    "stats.reports_desc": "автоматически сгенерировано",
    "stats.savings": "экономии времени",
    "stats.savings_desc": "на подготовку ESG отчетности",
    "stats.standards": "международных стандартов",
    "stats.standards_desc": "поддерживается платформой",
    
    // Advantages Section
    "advantages.title": "Преимущества платформы",
    "advantages.subtitle": "Sustainable Compass — это современное решение для ESG-анализа, созданное для эффективной работы с вашими данными.",
    "advantages.1.title": "Быстрая ESG диагностика",
    "advantages.1.desc": "Комплексная оценка текущего состояния компании по экологическим, социальным и управленческим критериям всего за несколько дней вместо обычных недель",
    "advantages.2.title": "Персонализированные рекомендации для развития", 
    "advantages.2.desc": "Получите детальный план улучшений и практические рекомендации, адаптированные под масштаб и потребности именно вашей компании",
    "advantages.3.title": "Простая подготовка к международным стандартам",
    "advantages.3.desc": "Подготовка к сертификации по международным стандартам (GRI, SASB, TCFD) с пошаговыми инструкциями и готовыми шаблонами",
    "advantages.4.title": "Современные цифровые решения",
    "advantages.4.desc": "Платформа автоматизирует сбор данных и генерацию отчетов, значительно сокращая время на подготовку ESG документации и повышая ее качество",
    
    // Target Audience
    "audience.title": "Кому подойдёт Sustainable Compass?",
    "audience.sme.title": "Собственники МСБ",
    "audience.sme.desc": "Малый и средний бизнес, который стремится соответствовать ESG-стандартам — от стартапов до региональных компаний",
    "audience.managers.title": "Руководители",
    "audience.managers.desc": "Топ-менеджмент и руководители отделов по корпоративной устойчивости, которым нужны данные для стратегических решений",
    "audience.investors.title": "Инвесторы",
    "audience.investors.desc": "Инвестиционные компании и частные инвесторы, которые учитывают ESG-критерии при принятии инвестиционных решений",
    "audience.cta": "Начать диагностику",
    
    // Diagnostics Section
    "diagnostics.title": "Проверьте свой уровень зрелости!",
    "diagnostics.subtitle": "Выберите подходящий тип диагностики для анализа ESG показателей вашего бизнеса",
    "diagnostics.basic.title": "Базовая ESG диагностика",
    "diagnostics.basic.subtitle": "Стартовый",
    "diagnostics.basic.desc": "Базовая оценка ESG-соответствия для небольших компаний",
    "diagnostics.basic.features.1": "Оценка по 15 ключевым показателям",
    "diagnostics.basic.features.2": "Анализ текущего состояния",
    "diagnostics.basic.features.3": "Базовые рекомендации",
    "diagnostics.basic.features.4": "Отчет на 25 страниц",
    "diagnostics.basic.features.5": "1 месяц поддержки",
    "diagnostics.smart.title": "Smart Plastic Zone",
    "diagnostics.smart.subtitle": "Рекомендуем",
    "diagnostics.smart.desc": "Комплексный анализ пластиковых материалов и управления отходами",
    "diagnostics.smart.features.1": "Полная диагностика пластиковых материалов",
    "diagnostics.smart.features.2": "Анализ экологической нагрузки производства",
    "diagnostics.smart.features.3": "Рекомендации по снижению воздействия",
    "diagnostics.smart.features.4": "Сертификация для экологических стандартов",
    "diagnostics.smart.features.5": "План внедрения на 12 месяцев",
    "diagnostics.smart.features.6": "3 месяца консультационной поддержки",
    "diagnostics.green.title": "Green Building Pro",
    "diagnostics.green.subtitle": "Премиум",
    "diagnostics.green.desc": "Полная оценка экологических зданий и сооружений",
    "diagnostics.green.features.1": "Анализ энергоэффективности зданий",
    "diagnostics.green.features.2": "Оценка экологических материалов",
    "diagnostics.green.features.3": "Сертификация зеленых стандартов",
    "diagnostics.green.features.4": "Оптимизация энергозатрат для бизнеса",
    "diagnostics.green.features.5": "Персональный менеджер проекта",
    "diagnostics.green.features.6": "6 месяцев поддержки и мониторинга",
    "diagnostics.carbon.title": "Углеродная нейтральность",
    "diagnostics.carbon.subtitle": "Экология",
    "diagnostics.carbon.desc": "Анализ и снижение углеродного следа для достижения нейтральности",
    "diagnostics.carbon.features.1": "Расчет углеродного следа",
    "diagnostics.carbon.features.2": "План снижения эмиссий",
    "diagnostics.carbon.features.3": "Сертификация углеродной нейтральности",
    "diagnostics.carbon.features.4": "Мониторинг выбросов CO2",
    "diagnostics.carbon.features.5": "Отчетность по климатическим рискам",
    "diagnostics.compliance.title": "ESG Соответствие",
    "diagnostics.compliance.subtitle": "Стандарты",
    "diagnostics.compliance.desc": "Полное соответствие международным ESG стандартам и требованиям",
    "diagnostics.compliance.features.1": "Соответствие GRI, SASB, TCFD",
    "diagnostics.compliance.features.2": "Подготовка ESG отчетности",
    "diagnostics.compliance.features.3": "Аудит устойчивого развития",
    "diagnostics.compliance.features.4": "Рейтинги ESG агентств",
    "diagnostics.compliance.features.5": "Непрерывный мониторинг соответствия",
    "diagnostics.transformation.title": "Цифровая трансформация",
    "diagnostics.transformation.subtitle": "Инновации",
    "diagnostics.transformation.desc": "Комплексная цифровая трансформация ESG процессов",
    "diagnostics.transformation.features.1": "Автоматизация ESG процессов",
    "diagnostics.transformation.features.2": "ИИ-аналитика устойчивости",
    "diagnostics.transformation.features.3": "Интеграция с корп. системами",
    "diagnostics.transformation.features.4": "Прогнозное моделирование",
    "diagnostics.transformation.features.5": "Блокчейн для ESG данных",
    "diagnostics.coming_soon": "Скоро",
    "diagnostics.learn_more": "Подробнее",
    
    // Services Section
    "services.footer": "Все услуги включают персональную консультацию и техническую поддержку",
    "services.consultation": "Бесплатная первичная консультация",
    "services.individual": "Индивидуальный подход к каждому клиенту",

    // Common
    "common.choose_plan": "Выбрать план",
    "common.contact": "Связаться",
    "common.popular": "Популярный",
    "common.language": "Язык",
    "common.theme": "Тема",
    "common.light_mode": "Светлая тема",
    "common.dark_mode": "Темная тема",
    "common.menu": "Меню",
    "common.navigation": "Навигация"
  },
  
  en: {
    // Navigation
    "nav.services": "Services",
    "nav.news": "News",
    "nav.about": "About",
    "nav.contacts": "Contacts", 
    "nav.dashboard": "Dashboard",
    "auth.login": "Login",
    "auth.logout": "Logout",
    
    // News Section
    "news.title": "News and Publications",
    "news.subtitle": "Current materials on ESG trends, sustainable development and best practices in Russian and international markets",
    "news.badge": "2025 News",
    "news.new": "New",
    "news.blog": "Blog",
    "news.view_all": "All news",
    "news.read_time": "min",
    
    // News Articles
    "news.article1.title": "New ESG reporting requirements in Russia: what will change in 2025",
    "news.article1.description": "The Central Bank of Russia presented updated ESG reporting standards for large public companies",
    "news.article1.readTime": "3",
    
    "news.article2.title": "Sustainable financing: how ESG criteria influence investment decisions",
    "news.article2.description": "Analysis of green financing trends and the impact of ESG ratings on the cost of capital for Russian companies",
    "news.article2.readTime": "5",
    
    "news.article3.title": "Digitalization of ESG processes: how technologies help companies achieve sustainable development goals",
    "news.article3.description": "Review of digital solutions for automating ESG data collection and improving reporting transparency",
    "news.article3.readTime": "4",
    
    "news.article4.title": "Practical recommendations for implementing ESG strategy for small and medium businesses",
    "news.article4.description": "Step-by-step guide to integrating ESG principles into SME operational activities",
    "news.article4.readTime": "6",
    
    // Contacts Section
    "contacts.title": "The first step to transforming your business starts here",
    "contacts.subtitle": "Starting point for any ESG project in Sustainable Compass",
    "contacts.email_placeholder": "Your corporate email",
    "contacts.info_title": "Contact Information",
    "contacts.email": "Email",
    "contacts.phone": "Phone",
    "contacts.address": "Address",
    "contacts.address_text": "Republic of Kazakhstan, Almaty\nZhibek Zholy St. 135, office 3rd floor",
    "contacts.problems_title": "What problems do companies face before working with Sustainable Compass?",
    "contacts.esg_title": "ESG is not just about ecology",
    "contacts.esg_subtitle": "It's a holistic approach",
    "contacts.problems.1": "I don't understand how to delve into business questions",
    "contacts.problems.2": "There are not enough experts for a deep diagnosis",
    "contacts.problems.3": "ESG requirements are growing, but you are not ready?",
    "contacts.problems.4": "Clients are becoming harder to find due to new ESG norms",
    "contacts.problems.5": "Banks are not working as expected with all new ecological norms",
    "contacts.problems.6": "Colleagues now require not only the price of the product",
    
    // Footer
    "footer.copyright": "© 2024 Sustainable Compass. All rights reserved.",
    "footer.links": "Privacy Policy • Terms of Use • Support",
    
    // Pricing General
    "pricing.title": "IT Solution Plans for Your Business",
    "pricing.subtitle": "Choose the right technology solution plan for your company's digital transformation and ESG standards implementation",
    "pricing.details": "See what's included ▼",
    "pricing.additional.title": "Additional Benefits of Our Plans",
    "pricing.additional.subtitle": "Regardless of the plan you choose, you get full spectrum support",
    "pricing.consultation.title": "Personal Consultation",
    "pricing.consultation.desc": "Free initial consultation with ESG expert to analyze your needs",
    "pricing.training.title": "Team Training",
    "pricing.training.desc": "Comprehensive training for your employees on ESG systems and standards",
    "pricing.security.title": "Data Security",
    "pricing.security.desc": "Highest level of corporate data protection according to international standards",
    "pricing.trial": "All plans include a free 14-day trial period",
    "pricing.payment": "Installment payment available • Discounts for educational institutions • Flexible conditions for startups",
    
    // Pricing Plans - English
    "pricing.plans.startup.name": "Startup",
    "pricing.plans.startup.subtitle": "Basic IT Solutions",
    "pricing.plans.startup.employees": "up to 50 employees",
    "pricing.plans.startup.feature1": "Basic ESG diagnostics",
    "pricing.plans.startup.feature2": "500 GB cloud storage",
    "pricing.plans.startup.feature3": "24/7 technical support",
    "pricing.plans.startup.feature4": "Automated reports",
    "pricing.plans.startup.feature5": "API integration",
    
    "pricing.plans.avantgard.name": "Avantgard",
    "pricing.plans.avantgard.subtitle": "Advanced AI Solutions",
    "pricing.plans.avantgard.employees": "50-500 employees",
    "pricing.plans.avantgard.feature1": "ESG analytics with AI",
    "pricing.plans.avantgard.feature2": "500 GB cloud storage",
    "pricing.plans.avantgard.feature3": "24/7 technical support",
    "pricing.plans.avantgard.feature4": "Automated reports",
    "pricing.plans.avantgard.feature5": "API integration",
    "pricing.plans.avantgard.feature6": "AI blockchain",
    
    "pricing.plans.quantum.name": "Quantum",
    "pricing.plans.quantum.subtitle": "Intelligent Management",
    "pricing.plans.quantum.employees": "500+ employees",
    "pricing.plans.quantum.feature1": "Full ESG ecosystem",
    "pricing.plans.quantum.feature2": "Unlimited storage",
    "pricing.plans.quantum.feature3": "Priority support",
    "pricing.plans.quantum.feature4": "Personal manager",
    "pricing.plans.quantum.feature5": "Corporate integration",
    
    "pricing.plans.enterprise.name": "Enterprise+",
    "pricing.plans.enterprise.subtitle": "Exclusive Solutions",
    "pricing.plans.enterprise.employees": "Corporations and government",
    "pricing.plans.enterprise.feature1": "Custom development",
    "pricing.plans.enterprise.feature2": "Dedicated infrastructure",
    "pricing.plans.enterprise.feature3": "Personal team",
    "pricing.plans.enterprise.feature4": "99.9% SLA",
    "pricing.plans.enterprise.feature5": "Comprehensive security",
    
    // ESG Components
    "esg.environmental.title": "Environmental",
    "esg.environmental.subtitle": "Environmental component",
    "esg.environmental.items.1": "Environmental reporting",
    "esg.environmental.items.2": "Waste management",
    "esg.environmental.items.3": "Energy efficiency",
    "esg.environmental.items.4": "Climate",
    "esg.environmental.items.5": "Biodiversity",
    "esg.social.title": "Social",
    "esg.social.subtitle": "Social component",
    "esg.social.items.1": "Human capital development",
    "esg.social.items.2": "Occupational health and safety",
    "esg.social.items.3": "Social investments",
    "esg.social.items.4": "Ethics",
    "esg.social.items.5": "Human rights",
    "esg.governance.title": "Governance",
    "esg.governance.subtitle": "Corporate governance",
    "esg.governance.items.1": "Corporate governance",
    "esg.governance.items.2": "Ethical principles",
    "esg.governance.items.3": "Risk management",
    "esg.governance.items.4": "Transparency",
    "esg.governance.items.5": "Anti-corruption policy",
    
    // Authentication
    "auth.authorization": "Authorization",
    "auth.loginOrRegisterDescription": "Login to your account or create a new account to access the ESG platform",
    "auth.register": "Register",
    "auth.loginTitle": "Login to your account",
    "auth.loginDescription": "Get access to ESG diagnostics analysis and personalized recommendations",
    "auth.registerTitle": "Create account",
    "auth.registerDescription": "Fill in the information to access ESG diagnostics",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Login",
    "auth.forgotPassword": "Forgot password or login?",
    "auth.contactSupport": "Write to",
    "auth.demoAccess": "Demo access",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.fullName": "Full name",
    "auth.fullNamePlaceholder": "John Smith",
    "auth.phone": "Phone",
    "auth.position": "Position",
    "auth.positionPlaceholder": "Sustainability Specialist",
    "auth.companyInfo": "Company information",
    "auth.companyName": "Company name",
    "auth.companyNamePlaceholder": "Green Technologies Inc.",
    "auth.industry": "Industry",
    "auth.selectIndustry": "Select industry",
    "auth.industries.energy": "Energy",
    "auth.industries.manufacturing": "Manufacturing",
    "auth.industries.finance": "Finance",
    "auth.industries.tech": "Technology",
    "auth.industries.other": "Other",
    "auth.companySize": "Company size",
    "auth.selectSize": "Select size",
    "auth.companySizes.small": "Up to 50 employees",
    "auth.companySizes.medium": "50-250 employees",
    "auth.companySizes.large": "250-1000 employees",
    "auth.companySizes.enterprise": "More than 1000 employees",
    "auth.city": "City",
    "auth.cityPlaceholder": "New York, USA",
    "auth.confirmPassword": "Confirm password",
    "auth.createAccount": "Create account",
    
    // Dashboard
    "dashboard.welcome": "Welcome, Aigul Nurdanova!",
    "dashboard.companyAnalysis": "ESG analysis of \"Green Technologies Almaty\" company",
    "dashboard.registration": "Registration",
    "dashboard.completion": "Completion",
    "dashboard.progressAnalysis": "Progress Analysis",
    "dashboard.clientReport": "Client Report",
    "dashboard.esgDiagnosticsBase": "ESG Diagnostics Base",
    "dashboard.esgAssessment": "Assessment of environmental, social and governance development",
    "dashboard.esgCompanyAnalysis": "ESG Company Analysis",
    "dashboard.new": "New",
    "dashboard.comprehensiveAnalysis": "Comprehensive analysis of social, environmental and governance performance indicators",
    "dashboard.completed": "Completed 26 of 36 questions",
    "dashboard.daysAgo": "15 days ago",
    "dashboard.monthsRemaining": "11 months remaining",
    "dashboard.smartPlasticZone": "Smart Plastic Zone",
    "dashboard.completedStatus": "Completed",
    "dashboard.environmentalSafety": "Assessment of intermediate or final environmental safety",
    "dashboard.completed34": "Completed 34 of 39 questions",
    "dashboard.dayAgo": "1 day ago",
    "dashboard.endMarch": "end March 15",
    "dashboard.greenBuildingAssessment": "Green Building Assessment",
    "dashboard.inProgress": "In Progress",
    "dashboard.buildingEfficiency": "Assessment of environmental efficiency of buildings and structures",
    "dashboard.completed7": "Completed 7 of 24 questions",
    "dashboard.continue": "Continue",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.startNewDiagnostics": "Start new diagnostics",
    "dashboard.downloadReports": "Download reports",
    "dashboard.contactSupport": "Contact support",
    "dashboard.personalInfo": "Personal Information",
    "dashboard.email": "Email:",
    "dashboard.dateJoined": "January: 15:47-2024",
    "dashboard.profileConfirmation": "Profile Confirmation",
    "dashboard.companyInfo": "Company Information",
    "dashboard.companyName": "\"Green Technologies Almaty\" LLC",
    "dashboard.ecologyForAll": "Ecology for everyone:",
    "dashboard.location": "Almaty, Kazakhstan",
    "dashboard.employees": "50-100 employees",
    "dashboard.website": "www.greentech-almaty.kz",
    "dashboard.companyConfirmation": "Company Confirmation",
    "dashboard.downloadAllReports": "Download all reports",
    
    // Hero Section
    "hero.title": "Sustainable Compass",
    "hero.subtitle": "Digital platform for ESG assessment and improvement",
    "hero.description": "Comprehensive business process diagnostics, ESG analysis according to international standards and personalized recommendations for sustainable development of your company",
    "hero.cta": "Try for free",
    "hero.demo": "About platform",
    "hero.stats_diagnostics": "diagnostics performed",
    "hero.feature1": "Fast ESG Diagnostics",
    "hero.feature2": "Personalized Recommendations",
    "hero.feature3": "Visual Reports for Investors",
    "hero.feature4": "International Standards",
    
    // Stats Section
    "stats.companies": "companies",
    "stats.companies_desc": "already use our platform",
    "stats.reports": "reports",
    "stats.reports_desc": "automatically generated",
    "stats.savings": "time savings",
    "stats.savings_desc": "on ESG reporting preparation",
    "stats.standards": "international standards",
    "stats.standards_desc": "supported by platform",
    
    // Advantages Section
    "advantages.title": "Platform Advantages",
    "advantages.subtitle": "Sustainable Compass is a modern ESG analysis solution designed for efficient work with your data.",
    "advantages.1.title": "Fast ESG Diagnostics",
    "advantages.1.desc": "Comprehensive assessment of company's current state according to environmental, social and governance criteria in just a few days instead of usual weeks",
    "advantages.2.title": "Personalized Development Recommendations",
    "advantages.2.desc": "Get detailed improvement plan and practical recommendations adapted to the scale and needs of your specific company",
    "advantages.3.title": "Simple Preparation for International Standards",
    "advantages.3.desc": "Preparation for certification according to international standards (GRI, SASB, TCFD) with step-by-step instructions and ready templates",
    "advantages.4.title": "Modern Digital Solutions", 
    "advantages.4.desc": "Platform automates data collection and report generation, significantly reducing time for ESG documentation preparation and improving its quality",
    
    // Target Audience
    "audience.title": "Who is Sustainable Compass for?",
    "audience.sme.title": "SME Owners",
    "audience.sme.desc": "Small and medium businesses that strive to meet ESG standards — from startups to regional companies",
    "audience.managers.title": "Managers",
    "audience.managers.desc": "Top management and department heads for corporate sustainability, who need data for strategic decisions",
    "audience.investors.title": "Investors",
    "audience.investors.desc": "Investment companies and private investors who consider ESG criteria in investment decisions",
    "audience.cta": "Start diagnostics",
    
    // Diagnostics Section
    "diagnostics.title": "Check your maturity level!",
    "diagnostics.subtitle": "Select the appropriate type of diagnostics for analyzing ESG indicators of your business",
    "diagnostics.basic.title": "Basic ESG Diagnostics",
    "diagnostics.basic.subtitle": "Starter",
    "diagnostics.basic.desc": "Basic ESG compliance assessment for small companies",
    "diagnostics.basic.features.1": "Assessment of 15 key indicators",
    "diagnostics.basic.features.2": "Analysis of current state",
    "diagnostics.basic.features.3": "Basic recommendations",
    "diagnostics.basic.features.4": "Report on 25 pages",
    "diagnostics.basic.features.5": "1 month of support",
    "diagnostics.smart.title": "Smart Plastic Zone",
    "diagnostics.smart.subtitle": "Recommended",
    "diagnostics.smart.desc": "Comprehensive analysis of plastic materials and waste management",
    "diagnostics.smart.features.1": "Full plastic material diagnostics",
    "diagnostics.smart.features.2": "Analysis of production environmental load",
    "diagnostics.smart.features.3": "Recommendations for reducing impact",
    "diagnostics.smart.features.4": "Certification for environmental standards",
    "diagnostics.smart.features.5": "Implementation plan for 12 months",
    "diagnostics.smart.features.6": "3 months of consulting support",
    "diagnostics.green.title": "Green Building Pro",
    "diagnostics.green.subtitle": "Premium",
    "diagnostics.green.desc": "Full assessment of ecological buildings and structures",
    "diagnostics.green.features.1": "Analysis of energy efficiency of buildings",
    "diagnostics.green.features.2": "Assessment of ecological materials",
    "diagnostics.green.features.3": "Certification of green standards",
    "diagnostics.green.features.4": "Optimization of energy costs for business",
    "diagnostics.green.features.5": "Personal project manager",
    "diagnostics.green.features.6": "6 months of support and monitoring",
    "diagnostics.carbon.title": "Carbon Neutrality",
    "diagnostics.carbon.subtitle": "Ecology",
    "diagnostics.carbon.desc": "Analysis and reduction of carbon footprint to achieve neutrality",
    "diagnostics.carbon.features.1": "Carbon footprint calculation",
    "diagnostics.carbon.features.2": "Emission reduction plan",
    "diagnostics.carbon.features.3": "Carbon neutrality certification",
    "diagnostics.carbon.features.4": "CO2 emissions monitoring",
    "diagnostics.carbon.features.5": "Climate risk reporting",
    "diagnostics.compliance.title": "ESG Compliance",
    "diagnostics.compliance.subtitle": "Standards",
    "diagnostics.compliance.desc": "Full compliance with international ESG standards and requirements",
    "diagnostics.compliance.features.1": "GRI, SASB, TCFD compliance",
    "diagnostics.compliance.features.2": "ESG reporting preparation",
    "diagnostics.compliance.features.3": "Sustainability audit",
    "diagnostics.compliance.features.4": "ESG agency ratings",
    "diagnostics.compliance.features.5": "Continuous compliance monitoring",
    "diagnostics.transformation.title": "Digital Transformation",
    "diagnostics.transformation.subtitle": "Innovation",
    "diagnostics.transformation.desc": "Comprehensive digital transformation of ESG processes",
    "diagnostics.transformation.features.1": "ESG process automation",
    "diagnostics.transformation.features.2": "AI sustainability analytics",
    "diagnostics.transformation.features.3": "Corporate system integration",
    "diagnostics.transformation.features.4": "Predictive modeling",
    "diagnostics.transformation.features.5": "Blockchain for ESG data",
    "diagnostics.coming_soon": "Coming Soon",
    "diagnostics.learn_more": "Learn more",
    
    // Services Section
    "services.footer": "All services include personal consultation and technical support",
    "services.consultation": "Free initial consultation",
    "services.individual": "Individual approach to each client",

    // Common
    "common.choose_plan": "Choose Plan",
    "common.contact": "Contact",
    "common.popular": "Popular",
    "common.language": "Language",
    "common.theme": "Theme",
    "common.light_mode": "Light Theme",
    "common.dark_mode": "Dark Theme",
    "common.menu": "Menu",
    "common.navigation": "Navigation"
  },
  
  kz: {
    // Navigation
    "nav.services": "Қызметтер",
    "nav.news": "Жаңалықтар",
    "nav.about": "Компания туралы",
    "nav.contacts": "Байланыстар",
    "nav.dashboard": "Басқару панелі",
    "auth.login": "Кіру",
    "auth.logout": "Шығу",
    
    // News Section
    "news.title": "Жаңалықтар мен басылымдар",
    "news.subtitle": "ESG трендтері, тұрақты даму және Ресей мен халықаралық нарықтың озық тәжірибелері туралы өзекті материалдар",
    "news.badge": "2025 Жаңалықтар",
    "news.new": "Жаңа",
    "news.blog": "Блог",
    "news.view_all": "Барлық жаңалықтар",
    "news.read_time": "мин",
    
    // News Articles
    "news.article1.title": "Ресейдегі ESG есептілігіне жаңа талаптар: 2025 жылы не өзгереді",
    "news.article1.description": "Ресей Орталық банкі ірі қоғамдық компаниялар үшін жаңартылған ESG есептілігі стандарттарын ұсынды",
    "news.article1.readTime": "3",
    
    "news.article2.title": "Тұрақты қаржыландыру: ESG критерийлері инвестициялық шешімдерге қалай әсер етеді",
    "news.article2.description": "Жасыл қаржыландыру тенденциялары мен ESG рейтингтерінің қазақстандық компаниялардың капитал құнына әсерін талдау",
    "news.article2.readTime": "5",
    
    "news.article3.title": "ESG процестерін цифрландыру: технологиялар компанияларға тұрақты даму мақсаттарына қол жеткізуге қалай көмектеседі",
    "news.article3.description": "ESG деректерін жинауды автоматтандыру және есептілік ашықтығын арттыру үшін цифрлық шешімдерге шолу",
    "news.article3.readTime": "4",
    
    "news.article4.title": "Шағын және орта бизнес үшін ESG стратегиясын енгізу бойынша практикалық ұсыныстар",
    "news.article4.description": "ШОБ компанияларының операциялық қызметіне ESG принциптерін интеграциялау бойынша қадамдық нұсқаулық",
    "news.article4.readTime": "6",
    
    // Contacts Section
    "contacts.title": "Сіздің бизнесіңізді трансформациялаудың бірінші қадамы осы жерден басталады",
    "contacts.subtitle": "Sustainable Compass-тағы кез келген ESG жобасының бастау нүктесі",
    "contacts.email_placeholder": "Сіздің корпоративтік поштаңыз",
    "contacts.info_title": "Байланыс ақпараты",
    "contacts.email": "Электрондық пошта",
    "contacts.phone": "Телефон",
    "contacts.address": "Мекенжай",
    "contacts.address_text": "Қазақстан Республикасы, Алматы қ.\nЖібек жолы көш. 135, кеңсе 3-қабат",
    "contacts.problems_title": "Sustainable Compass-пен жұмыс істеуге дейін компаниялар қандай проблемаларға тап болады?",
    "contacts.esg_title": "ESG тек экология емес",
    "contacts.esg_subtitle": "Бұл кешенді көзқарас",
    "contacts.problems.1": "Бизнес мәселелерін терең зерттеуді қалай бастау керектігін түсінбеймін",
    "contacts.problems.2": "Терең диагностика үшін сарапшылар жеткіліксіз",
    "contacts.problems.3": "ESG талаптары өсуде, бірақ сіз дайын емессіз бе?",
    "contacts.problems.4": "Жаңа ESG нормалары салдарынан клиенттерді табу қиындайды",
    "contacts.problems.5": "Банктер барлық жаңа экологиялық нормаларға сәйкестік сияқты күтілгендей жұмыс істемейді",
    "contacts.problems.6": "Әріптестер енді тек өнімнің бағасын ғана емес, басқаны да талап ете бастады",
    
    // Footer
    "footer.copyright": "© 2024 Sustainable Compass. Барлық құқықтар қорғалған.",
    "footer.links": "Құпиялылық саясаты • Пайдалану шарттары • Қолдау",
    
    // Pricing General
    "pricing.title": "Сіздің бизнесіңіз үшін IT шешімдер жоспарлары",
    "pricing.subtitle": "Компанияңыздың цифрлық трансформациясы және ESG стандарттарын енгізу үшін дұрыс технологиялық шешім жоспарын таңдаңыз",
    "pricing.details": "Не кіретінін көру ▼",
    "pricing.additional.title": "Біздің жоспарларымыздың қосымша артықшылықтары",
    "pricing.additional.subtitle": "Қай жоспарды таңдасаңыз да, толық спектрлі қолдау аласыз",
    "pricing.consultation.title": "Жеке кеңес",
    "pricing.consultation.desc": "Сіздің қажеттіліктеріңізді талдау үшін ESG сарапшысымен тегін алғашқы кеңес",
    "pricing.training.title": "Команда дайындау",
    "pricing.training.desc": "Қызметкерлеріңізді ESG жүйелері мен стандарттарымен жұмыс істеуге кешенді дайындау",
    "pricing.security.title": "Деректер қауіпсіздігі",
    "pricing.security.desc": "Халықаралық стандарттарға сәйкес корпоративтік деректерді қорғаудың ең жоғары деңгейі",
    "pricing.trial": "Барлық жоспарларға 14 күндік тегін сынақ кезеңі кіреді",
    "pricing.payment": "Бөліп төлеу мүмкін • Білім беру мекемелеріне жеңілдіктер • Стартаптар үшін икемді шарттар",
    
    // Pricing Plans - Kazakh
    "pricing.plans.startup.name": "Стартап",
    "pricing.plans.startup.subtitle": "Негізгі IT шешімдері",
    "pricing.plans.startup.employees": "50-ге дейін қызметкерлер",
    "pricing.plans.startup.feature1": "Негізгі ESG диагностикасы",
    "pricing.plans.startup.feature2": "500 ГБ бұлтты сақтау",
    "pricing.plans.startup.feature3": "24/7 техникалық қолдау",
    "pricing.plans.startup.feature4": "Автоматты есептер",
    "pricing.plans.startup.feature5": "API интеграциясы",
    
    "pricing.plans.avantgard.name": "Avantgard",
    "pricing.plans.avantgard.subtitle": "ЖИ-мен кеңейтілген шешімдер",
    "pricing.plans.avantgard.employees": "50-500 қызметкерлер",
    "pricing.plans.avantgard.feature1": "ЖИ-мен ESG аналитикасы",
    "pricing.plans.avantgard.feature2": "500 ГБ бұлтты сақтау",
    "pricing.plans.avantgard.feature3": "24/7 техникалық қолдау",
    "pricing.plans.avantgard.feature4": "Автоматталған есептер",
    "pricing.plans.avantgard.feature5": "API интеграциясы",
    "pricing.plans.avantgard.feature6": "ЖИ блокчейн",
    
    "pricing.plans.quantum.name": "Quantum",
    "pricing.plans.quantum.subtitle": "Ақылды басқару",
    "pricing.plans.quantum.employees": "500+ қызметкерлер",
    "pricing.plans.quantum.feature1": "Толық ESG экожүйесі",
    "pricing.plans.quantum.feature2": "Шексіз сақтау",
    "pricing.plans.quantum.feature3": "Басымдықты қолдау",
    "pricing.plans.quantum.feature4": "Жеке менеджер",
    "pricing.plans.quantum.feature5": "Корпоративтік интеграция",
    
    "pricing.plans.enterprise.name": "Enterprise+",
    "pricing.plans.enterprise.subtitle": "Эксклюзивті шешімдер",
    "pricing.plans.enterprise.employees": "Корпорациялар мен мемсектор",
    "pricing.plans.enterprise.feature1": "Жеке әзірлеу",
    "pricing.plans.enterprise.feature2": "Арнайы инфрақұрылым",
    "pricing.plans.enterprise.feature3": "Жеке команда",
    "pricing.plans.enterprise.feature4": "99.9% SLA",
    "pricing.plans.enterprise.feature5": "Кешенді қауіпсіздік",
    
    // ESG Components
    "esg.environmental.title": "Environmental",
    "esg.environmental.subtitle": "Экологиялық құрауыш",
    "esg.environmental.items.1": "Экологиялық есептілік",
    "esg.environmental.items.2": "Қалдықтарды басқару",
    "esg.environmental.items.3": "Энергия тиімділігі",
    "esg.environmental.items.4": "Климат",
    "esg.environmental.items.5": "Биоалуандық",
    "esg.social.title": "Social",
    "esg.social.subtitle": "Әлеуметтік құрауыш",
    "esg.social.items.1": "Адами капиталды дамыту",
    "esg.social.items.2": "Еңбекті қорғау және қауіпсіздік",
    "esg.social.items.3": "Әлеуметтік инвестициялар",
    "esg.social.items.4": "Этика",
    "esg.social.items.5": "Адам құқықтары",
    "esg.governance.title": "Governance",
    "esg.governance.subtitle": "Корпоративтік басқару",
    "esg.governance.items.1": "Корпоративтік басқару",
    "esg.governance.items.2": "Этикалық принциптер",
    "esg.governance.items.3": "Тәуекелдерді басқару",
    "esg.governance.items.4": "Ашықтық",
    "esg.governance.items.5": "Сыбайлас жемқорлыққа қарсы саясат",
    
    // Authentication
    "auth.authorization": "Авторизация",
    "auth.loginOrRegisterDescription": "ESG платформасына қол жеткізу үшін есептік жазбаңызға кіріңіз немесе жаңа есептік жазба жасаңыз",
    "auth.register": "Тіркеу",
    "auth.loginTitle": "Есептік жазбаңызға кіру",
    "auth.loginDescription": "ESG диагностикасы талдауы мен жеке ұсыныстарға қол жеткізіңіз",
    "auth.registerTitle": "Есептік жазба жасау",
    "auth.registerDescription": "ESG диагностикасына қол жеткізу үшін ақпаратты толтырыңыз",
    "auth.email": "Электрондық пошта",
    "auth.password": "Құпия сөз",
    "auth.loginButton": "Кіру",
    "auth.forgotPassword": "Құпия сөзді немесе логинді ұмыттыңыз ба?",
    "auth.contactSupport": "Жазыңыз",
    "auth.demoAccess": "Демо қол жеткізу",
    "auth.invalidCredentials": "Қате электрондық пошта немесе құпия сөз",
    "auth.fullName": "Толық аты-жөні",
    "auth.fullNamePlaceholder": "Айгүл Нұрданова",
    "auth.phone": "Телефон",
    "auth.position": "Лауазым",
    "auth.positionPlaceholder": "Тұрақты даму маманы",
    "auth.companyInfo": "Компания туралы ақпарат",
    "auth.companyName": "Компания атауы",
    "auth.companyNamePlaceholder": "«Жасыл Технологиялар» ЖШС",
    "auth.industry": "Сала",
    "auth.selectIndustry": "Саланы таңдаңыз",
    "auth.industries.energy": "Энергетика",
    "auth.industries.manufacturing": "Өндіріс",
    "auth.industries.finance": "Қаржы",
    "auth.industries.tech": "Технологиялар",
    "auth.industries.other": "Басқа",
    "auth.companySize": "Компания көлемі",
    "auth.selectSize": "Көлемді таңдаңыз",
    "auth.companySizes.small": "50-ге дейін қызметкерлер",
    "auth.companySizes.medium": "50-250 қызметкерлер",
    "auth.companySizes.large": "250-1000 қызметкерлер",
    "auth.companySizes.enterprise": "1000-нан астам қызметкерлер",
    "auth.city": "Қала",
    "auth.cityPlaceholder": "Алматы, Қазақстан",
    "auth.confirmPassword": "Құпия сөзді растау",
    "auth.createAccount": "Есептік жазба жасау",
    
    // Dashboard
    "dashboard.welcome": "Қош келдіңіз, Айгүл Нұрданова!",
    "dashboard.companyAnalysis": "«Жасыл Технологиялар Алматы» компаниясының ESG талдауы",
    "dashboard.registration": "Тіркеу",
    "dashboard.completion": "Толтыру",
    "dashboard.progressAnalysis": "Прогресс талдауы",
    "dashboard.clientReport": "Клиенттерге есеп",
    "dashboard.esgDiagnosticsBase": "ESG диагностикасының негіздері",
    "dashboard.esgAssessment": "Экологиялық, әлеуметтік және басқару дамуын бағалау",
    "dashboard.esgCompanyAnalysis": "Компаниялардың ESG талдауы",
    "dashboard.new": "Жаңа",
    "dashboard.comprehensiveAnalysis": "Әлеуметтік, экологиялық және басқару қызметінің көрсеткіштерінің кешенді талдауы",
    "dashboard.completed": "36 сұрақтың 26-сы толтырылды",
    "dashboard.daysAgo": "15 күн бұрын",
    "dashboard.monthsRemaining": "11 ай қалды",
    "dashboard.smartPlasticZone": "Smart Plastic Zone",
    "dashboard.completedStatus": "Аяқталды",
    "dashboard.environmentalSafety": "Аралық немесе түпкілікті экологиялық қауіпсіздікті бағалау",
    "dashboard.completed34": "39 сұрақтың 34-і толтырылды",
    "dashboard.dayAgo": "1 күн бұрын",
    "dashboard.endMarch": "наурыз 15 аяғы",
    "dashboard.greenBuildingAssessment": "Green Building Assessment",
    "dashboard.inProgress": "Үрдісте",
    "dashboard.buildingEfficiency": "Ғимараттар мен құрылыстардың экологиялық тиімділігін бағалау",
    "dashboard.completed7": "24 сұрақтың 7-сі толтырылды",
    "dashboard.continue": "Жалғастыру",
    "dashboard.quickActions": "Жылдам әрекеттер",
    "dashboard.startNewDiagnostics": "Жаңа диагностика бастау",
    "dashboard.downloadReports": "Есептерді жүктеу",
    "dashboard.contactSupport": "Қолдау қызметімен байланысу",
    "dashboard.personalInfo": "Жеке ақпарат",
    "dashboard.email": "Электрондық пошта:",
    "dashboard.dateJoined": "Қаңтар: 15:47-2024",
    "dashboard.profileConfirmation": "Профильді растау",
    "dashboard.companyInfo": "Компания туралы ақпарат",
    "dashboard.companyName": "«Жасыл Технологиялар Алматы» ЖШС",
    "dashboard.ecologyForAll": "Барлығына арналған экология:",
    "dashboard.location": "Алматы, Қазақстан",
    "dashboard.employees": "50-100 қызметкерлер",
    "dashboard.website": "www.greentech-almaty.kz",
    "dashboard.companyConfirmation": "Компанияны растау",
    "dashboard.downloadAllReports": "Барлық есептерді жүктеу",
    
    // Hero Section
    "hero.title": "Sustainable Compass",
    "hero.subtitle": "ESG көрсеткіштерін бағалау және жақсарту үшін цифрлық платформа",
    "hero.description": "Бизнес-процестердің кешенді диагностикасы, халықаралық стандарттар бойынша ESG талдауы және компанияңыздың тұрақты дамуы үшін жеке ұсыныстар",
    "hero.cta": "Тегін сынап көру",
    "hero.demo": "Платформа туралы",
    "hero.stats_diagnostics": "диагностика жүргізілді",
    "hero.feature1": "Жылдам ESG диагностикасы",
    "hero.feature2": "Жеке ұсыныстар",
    "hero.feature3": "Инвесторлар үшін визуалды есептер",
    "hero.feature4": "Халықаралық стандарттар",
    
    // Stats Section
    "stats.companies": "компаниялар",
    "stats.companies_desc": "біздің платформамызды пайдаланады",
    "stats.reports": "есептер",
    "stats.reports_desc": "автоматты түрде жасалды",
    "stats.savings": "уақыт үнемдеу",
    "stats.savings_desc": "ESG есептілігін дайындауға",
    "stats.standards": "халықаралық стандарттар",
    "stats.standards_desc": "платформа қолдайды",
    
    // Advantages Section
    "advantages.title": "Платформа артықшылықтары",
    "advantages.subtitle": "Sustainable Compass — деректеріңізбен тиімді жұмыс істеуге арналған заманауи ESG талдау шешімі.",
    "advantages.1.title": "Жылдам ESG диагностикасы",
    "advantages.1.desc": "Экологиялық, әлеуметтік және басқару критерийлері бойынsha компанияның ағымдағы жағдайын кешенді бағалау әдеттегі апталар орнына бірнеше күн ішінде",
    "advantages.2.title": "Даму үшін жеке ұсыныстар",
    "advantages.2.desc": "Нақ сіздің компанияңыздың ауқымы мен қажеттіліктеріне бейімделген жақсарту жоспары мен практикалық ұсыныстарды алыңыз",
    "advantages.3.title": "Халықаралық стандарттарға қарапайым дайындық",
    "advantages.3.desc": "Қадамдық нұсқаулықтар мен дайын үлгілермен халықаралық стандарттарға (GRI, SASB, TCFD) сертификаттауға дайындық",
    "advantages.4.title": "Заманауи цифрлық шешімдер",
    "advantages.4.desc": "Платформа деректерді жинау мен есеп жасауды автоматтандырады, ESG құжаттамасын дайындау уақытын айтарлықтай қысқартады және оның сапасын арттырады",
    
    // Target Audience
    "audience.title": "Sustainable Compass кімге арналған?",
    "audience.sme.title": "ШОБ иелері",
    "audience.sme.desc": "ESG стандарттарына сәйкес келуге тырысатын шағын және орта бизнес — стартаптардан аймақтық компанияларға дейін",
    "audience.managers.title": "Басшылар",
    "audience.managers.desc": "Стратегиялық шешімдер қабылдау үшін деректер қажет корпоративтік тұрақтылық бөлімдерінің топ-менеджменті мен басшылары",
    "audience.investors.title": "Инвесторлар",
    "audience.investors.desc": "Инвестициялық шешімдер қабылдау кезінде ESG критерийлерін ескеретін инвестициялық компаниялар мен жеке инвесторлар",
    "audience.cta": "Диагностиканы бастау",
    
    // Diagnostics Section
    "diagnostics.title": "Жетілу деңгейіңізді тексеріңіз!",
    "diagnostics.subtitle": "Бизнесіңіздің ESG көрсеткіштерін талдау үшін тиісті диагностика түрін таңдаңыз",
    "diagnostics.basic.title": "Негізгі ESG диагностикасы",
    "diagnostics.basic.subtitle": "Бастаушы",
    "diagnostics.basic.desc": "Шағын компаниялар үшін негізгі ESG сәйкестігін бағалау",
    "diagnostics.basic.features.1": "15 негізгі көрсеткіш бойынша бағалау",
    "diagnostics.basic.features.2": "Ағымдағы жағдайды талдау",
    "diagnostics.basic.features.3": "Негізгі ұсыныстар",
    "diagnostics.basic.features.4": "25 беттік есеп",
    "diagnostics.basic.features.5": "1 ай қолдау",
    "diagnostics.smart.title": "Smart Plastic Zone",
    "diagnostics.smart.subtitle": "Ұсынамыз",
    "diagnostics.smart.desc": "Пластик материалдары мен қалдықтарды басқарудың кешенді талдауы",
    "diagnostics.smart.features.1": "Пластик материалдарының толық диагностикасы",
    "diagnostics.smart.features.2": "Өндіріс экологиялық жүктемесін талдау",
    "diagnostics.smart.features.3": "Әсерді азайту бойынша ұсыныстар",
    "diagnostics.smart.features.4": "Экологиялық стандарттарға сертификаттау",
    "diagnostics.smart.features.5": "12 айға енгізу жоспары",
    "diagnostics.smart.features.6": "3 ай кеңес беру қолдауы",
    "diagnostics.green.title": "Green Building Pro",
    "diagnostics.green.subtitle": "Премиум",
    "diagnostics.green.desc": "Экологиялық ғимараттар мен құрылыстарды толық бағалау",
    "diagnostics.green.features.1": "Ғимараттардың энергия тиімділігін талдау",
    "diagnostics.green.features.2": "Экологиялық материалдарды бағалау",
    "diagnostics.green.features.3": "Жасыл стандарттарды сертификаттау",
    "diagnostics.green.features.4": "Бизнес үшін энергия шығындарын оңтайландыру",
    "diagnostics.green.features.5": "Жеке жоба менеджері",
    "diagnostics.green.features.6": "6 ай қолдау және мониторинг",
    "diagnostics.carbon.title": "Көміртекті бейтараптық",
    "diagnostics.carbon.subtitle": "Экология",
    "diagnostics.carbon.desc": "Бейтараптыққа жету үшін көміртекті ізді талдау және азайту",
    "diagnostics.carbon.features.1": "Көміртекті ізді есептеу",
    "diagnostics.carbon.features.2": "Шығарындыларды азайту жоспары",
    "diagnostics.carbon.features.3": "Көміртекті бейтараптыққа сертификаттау",
    "diagnostics.carbon.features.4": "CO2 шығарындыларын бақылау",
    "diagnostics.carbon.features.5": "Климаттық тәуекелдер бойынша есептілік",
    "diagnostics.compliance.title": "ESG сәйкестігі",
    "diagnostics.compliance.subtitle": "Стандарттар",
    "diagnostics.compliance.desc": "Халықаралық ESG стандарттары мен талаптарына толық сәйкестік",
    "diagnostics.compliance.features.1": "GRI, SASB, TCFD сәйкестігі",
    "diagnostics.compliance.features.2": "ESG есептілігін дайындау",
    "diagnostics.compliance.features.3": "Тұрақты даму аудиті",
    "diagnostics.compliance.features.4": "ESG агенттіктерінің рейтингтері",
    "diagnostics.compliance.features.5": "Сәйкестіктің үздіксіз бақылауы",
    "diagnostics.transformation.title": "Цифрлық трансформация",
    "diagnostics.transformation.subtitle": "Инновациялар",
    "diagnostics.transformation.desc": "ESG процестерінің кешенді цифрлық трансформациясы",
    "diagnostics.transformation.features.1": "ESG процестерін автоматтандыру",
    "diagnostics.transformation.features.2": "ЖИ тұрақтылық аналитикасы",
    "diagnostics.transformation.features.3": "Корпоративтік жүйелерге интеграция",
    "diagnostics.transformation.features.4": "Болжамды модельдеу",
    "diagnostics.transformation.features.5": "ESG деректері үшін блокчейн",
    "diagnostics.coming_soon": "Жақында",
    "diagnostics.learn_more": "Толығырақ",
    
    // Services Section
    "services.footer": "Барлық қызметтерге жеке кеңес беру және техникалық қолдау кіреді",
    "services.consultation": "Тегін алғашқы кеңес",
    "services.individual": "Әр клиентке жеке көзқарас",

    // Common
    "common.choose_plan": "Жоспар таңдау",
    "common.contact": "Байланысу",
    "common.popular": "Танымал",
    "common.language": "Тіл",
    "common.theme": "Тема",
    "common.light_mode": "Ашық тема",
    "common.dark_mode": "Қараңғы тема",
    "common.menu": "Мәзір",
    "common.navigation": "Навигация"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}